--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/matcracker/Elevator
build-by-default: true
branches:
- master
projects:
  Elevator:
    path: ""
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: 1.0.0
...
